# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e012c6cb7c8ec14fbaf9cb576b5d8bdc5367977b350e820bae3bdfcb473033c46a36c45d278fc033a862a56ded0cc24683844be479fcd8a7edb8a21d28fed7

test:
  secret_key_base: da500ca062ba1e15c0ad097a2563ef22f76d547a3ae259e443f4a2b0c1d749586f82788178e227e13fa5c4be9c577668851195951157792c41be59c06fc9918e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
